GyldendalDigital/kobber

.idea/workspace.xml, packages/kobber-audio-recorder/README.md, packages/kobber-audio-recorder/index.html, packages/kobber-audio-recorder/package.json, packages/kobber-audio-recorder/src/audio-recorder-svelte/AudioRecorder.svelte, yarn.lock
- Added basic readme for usage, needs more work but fine for now
- Implemented reactive design
- Added translations
- Some cleanup and clarifying comments
=> Audio Recorder design and cleanup

packages/kobber-components/src/aspect-ratio/AspectRatio.stories.ts, packages/kobber-components/src/badge/Badge.stories.ts, packages/kobber-components/src/button/Button.stories.ts, packages/kobber-components/src/dialog/Dialog.stories.ts, packages/kobber-components/src/dropdown/Dropdown.stories.ts, packages/kobber-components/src/wiki-accordion/Accordion.stories.ts, packages/kobber-components/src/wiki-list/List.stories.ts
=> Storybook category in development

packages/kobber-components/src/carousel/Carousel.ts, packages/kobber-components/src/carousel/NavigationButtons.ts, packages/kobber-components/src/layouts/patterns/Patterns.stories.ts
- add corrections for Safari 16
- correct theme usage
- add aria-label to buttons
=> Final carousel corrections

packages/kobber-audio-recorder/src/audio-recorder-svelte/AudioRecorder.svelte
- Fixed bug where previous data did not expand the view
- Made minor design changes like adjusting size of certain elements, and making the overall look more flat
=> audio-recorder init bug and design changes

packages/kobber-audio-recorder/index.html, packages/kobber-audio-recorder/src/audio-recorder-svelte/AudioRecorder.svelte
improved data handling, fixed several bugs and made the whole save data system more sturdy!
=> audio-recorder data handling

packages/kobber-audio-recorder/index.html, packages/kobber-audio-recorder/src/audio-recorder-svelte/AudioHelpers.js, packages/kobber-audio-recorder/src/audio-recorder-svelte/AudioRecorder.svelte
Went back to previous data output because of the largeFileStorageApi not accepting an array of blobs. Instead, I put all the blobs into a single blob, with some basic header logic to deserialize them when they are loaded into the recorder :)
=> audio-recorder blobs n headers

packages/kobber-audio-recorder/package.json, packages/kobber-audio-recorder/src/audio-recorder-svelte/AudioHelpers.js, packages/kobber-audio-recorder/vitehttps.config.js, yarn.lock
iPad bugfix, and added improvements to the dev experience when debugging with an iPad
=> audio-recorder iPad bugfix

apps/wiki/app/(routes)/komponenter/components.meta.ts
=> Fix typo: tviklingsprosessen -> utviklingsprosessen

.idea/workspace.xml, packages/kobber-audio-recorder/src/audio-recorder-svelte/AudioHelpers.js, packages/kobber-audio-recorder/src/audio-recorder-svelte/AudioRecorder.svelte
application/octet-stream is given as a default type from the largeFileApi, meaning I have to infer it being audio to get it to work
=> audio-recorder application/octet-stream bug

packages/kobber-audio-recorder/src/audio-recorder-svelte/AudioRecorder.svelte
Improved touch interactions and adjusted empty save-state
=> audio-recorder interactions and saves

apps/wiki/app/(testing)/dark/dark-mode-trigger.tsx, apps/wiki/app/(testing)/dark/page.tsx, apps/wiki/app/layout.tsx
=> wiki: use dark mode

packages/kobber-audio-recorder/src/audio-recorder-svelte/AudioRecorder.svelte
exposing isRecording to send correct data to Skolestudio navigation
=> audio-recorder isRecording exposed

.changeset/smart-cameras-hunt.md, apps/storybook-web-components/public/global.css, apps/wiki/components/global/router-link.tsx, apps/wiki/components/navigation/nav-link.tsx, apps/wiki/components/navigation/small-screen-nav.module.css, apps/wiki/components/navigation/small-screen-nav.tsx, apps/wiki/components/navigation/top-nav.module.css, apps/wiki/components/navigation/top-nav.tsx, packages/kobber-components/src/button/Button.stories.ts, packages/kobber-components/src/button/Button.styles.ts, packages/kobber-components/src/text/Text.stories.ts, packages/kobber-components/src/text/link/Link.core.ts, packages/kobber-components/src/text/link/Link.react.tsx, packages/kobber-components/src/text/link/Link.styles.ts, packages/kobber-components/src/text/link/Link.ts
kobber link will use button element if href is falsy and onclick is set
=> components: link as button

packages/kobber-base/README.md, packages/kobber-components/README.md, packages/kobber-components/src/button/Button.core.ts, packages/kobber-components/src/button/Button.react.tsx, packages/kobber-components/src/button/Button.styles.ts, packages/kobber-components/src/button/Button.ts, packages/kobber-icons/README.md
Corrections necessary for the upcoming kobber-radio-button component.
=> Some kobber-button corrections

apps/docs/app/(web)/(routes)/tokens/drawSlope.ts, apps/docs/lib/theme.ts, apps/storybook-web-components/.storybook/kobberTheme.js, packages/kobber-base/README.md, packages/kobber-components/src/accordion/Accordion.styles.ts, packages/kobber-components/src/aspect-ratio/AspectRatio.stories.ts, packages/kobber-components/src/badge/Badge.ts, packages/kobber-components/src/base/kobber-element.ts, packages/kobber-components/src/carousel/config.ts, packages/kobber-components/src/grid/Grid.stories.ts, packages/kobber-components/src/grid/story/ExampleCard.ts, packages/kobber-components/src/layouts/box-layout/BoxLayout.ts, packages/kobber-components/src/layouts/card-layout/config.ts, packages/kobber-components/src/layouts/horizontal-layout/config.ts, packages/kobber-components/src/layouts/story/ExampleCard.ts, packages/kobber-components/src/layouts/story/ExampleSurface.ts, packages/kobber-components/src/list/List.styles.ts, packages/kobber-components/src/list/ListItem.styles.ts, packages/kobber-components/src/radio/Radio.stories.ts, packages/kobber-components/src/story/ExampleCard.ts, packages/kobber-components/src/story/story-summary.ts, packages/kobber-components/src/utils/contrast.test.ts, packages/kobber-components/src/utils/theme-context.ts, packages/kobber-icons/tsup-scripts/make-react-ssr-safe-component.ts, packages/kobber-icons/tsup-scripts/make-web-component.ts
Trengs for å kjøre komponenter i svelte
=> components: add missing .js extensions

packages/kobber-components/src/aspect-ratio/AspectRatio.stories.ts, packages/kobber-components/src/aspect-ratio/AspectRatioWiki.mdx, packages/kobber-components/src/carousel/Carousel.stories.ts, packages/kobber-components/src/dialog/Dialog.stories.ts, packages/kobber-components/src/grid/Grid.stories.ts, packages/kobber-components/src/layouts/card-layout/CardLayout.mdx, packages/kobber-components/src/layouts/card-layout/CardLayout.stories.ts, packages/kobber-components/src/layouts/horizontal-layout/HorizontalLayout.stories.ts, packages/kobber-components/src/layouts/patterns/Patterns.stories.ts, packages/kobber-components/src/progress-bar/ProgressBar.stories.ts
As per designer's wish
(https://gyldendal.slack.com/archives/C06B5N7H36E/p1744194163897239)
=> Re-order storybook menu

apps/docs/app/(web)/(routes)/_hero-banner.module.css, apps/docs/components/feature-box/feature-box.module.css, apps/docs/components/footer.module.css, apps/docs/components/navigation/nav-bar/nav-bar.module.css, apps/docs/components/navigation/side-menu/side-menu.module.css, apps/docs/components/navigation/small-screen-nav/small-screen-nav.module.css, apps/docs/components/page-builder/sections/color-list/color-list-block.module.css, apps/docs/components/page-builder/sections/contact-list-block.module.css, apps/docs/styles/globals.css, apps/docs/styles/reset.css, packages/kobber-icons/src/icon/index.mdx, packages/kobber-stylelint/package.json, yarn.lock
As mentioned in [Slack [](thread](https://gyldendal.slack.com/archives/C06B5N7H36E/p1756717381881149).)
=> Misc cleanup

apps/storybook-web-components/package.json, yarn.lock
=> Add kobber-icons to storybook's devdependencies

packages/kobber-audio-recorder/src/audio-recorder-svelte/AudioRecorder.svelte
changed ondatavailable to run in 1 second chunks instead of one big chunk at the end
=> audio-recorder-macos-safari-bugfix

packages/kobber-components/src/badge-icon/BadgeIcon.stories.ts, packages/kobber-components/src/badge-icon/BadgeIcon.styles.ts, packages/kobber-components/src/badge-icon/BadgeIcon.ts, packages/kobber-components/src/badge/Badge.core.ts, packages/kobber-components/src/badge/Badge.stories.ts, packages/kobber-components/src/badge/Badge.styles.ts, packages/kobber-components/src/badge/Badge.ts, packages/kobber-components/src/base/internal/buttonUtils.ts, packages/kobber-components/src/base/utilities/invertColorVariant.ts, packages/kobber-components/src/button/Button.stories.ts, packages/kobber-components/src/button/Button.styles.ts, packages/kobber-components/src/button/Button.ts, packages/kobber-components/src/checkbox/Checkbox.stories.ts, packages/kobber-components/src/checkbox/checkbox-input/CheckboxInput.ts, packages/kobber-components/src/checkbox/checkbox-input/checkboxInput.styles.ts, packages/kobber-components/src/divider/Divider.styles.ts, packages/kobber-components/src/index.css, packages/kobber-components/src/link/Link.stories.ts, packages/kobber-components/src/link/Link.styles.ts, packages/kobber-components/src/link/Link.ts, packages/kobber-components/src/radio/Radio.stories.ts, packages/kobber-components/src/radio/radio-input-control/RadioInputControl.styles.ts, packages/kobber-components/src/radio/radio-input-control/RadioInputControl.ts, packages/kobber-components/src/radio/radio-input/RadioInput.styles.ts, packages/kobber-components/src/radio/radio-input/RadioInput.ts
=> Use text label internally in components

packages/kobber-components/src/checkbox/Checkbox.core.ts, packages/kobber-components/src/checkbox/checkbox-input/CheckboxInput.ts, packages/kobber-components/src/checkbox/checkbox-input/checkboxInput.styles.ts, packages/kobber-components/src/index.css
This corrects bug mentioned in [Slack Prosjektplan](https://gyldendal.slack.com/archives/C089YD56Q1G/p1758806369458159?thread_ts=1744276504.652039&cid=C089YD56Q1G).
=> Correct checkbox icon color
